version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql  # Configuração para o host do MySQL
    depends_on:
      - mysql  # Dependência do serviço MySQL

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliveryOnline
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
