version: '3.8'

services:
  app:
    container_name: fm3buffet
    image: theussm/fm3buffet:latest
    ports:
      - "3000:3000"  # Porta pública : Porta interna do contêiner
    environment:
      - AMBIENTE=dev
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=deliveryOnline
    depends_on:
      - db
    volumes:
      - images:/app/server/public/images  # Volume para persistir imagens
    networks:
      my_custom_network:
        ipv4_address: 172.18.0.22  # IP fixo para o contêiner app

  db:
    image: mysql:8.0
    container_name: fm3buffet_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: deliveryOnline
    ports:
      - "3306:3306"  # Porta pública : Porta interna do contêiner
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/backup.sh:/docker-entrypoint-initdb.d/backup.sh
      - ./docker/backups:/backups
      - ./docker/mysql_logs:/var/log/mysql  # Volume para logs do MySQL
    networks:
      my_custom_network:

volumes:
  db_data:
  mysql_logs:
  images:  # Novo volume para as imagens da aplicação

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16