-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 19:52:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema deliveryOnline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliveryOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deliveryOnline` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `deliveryOnline` ;

-- -----------------------------------------------------
-- Table `deliveryOnline`.`categoria`
-- -----------------------------------------------------

ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '123';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `deliveryOnline`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `icone` VARCHAR(45) NULL DEFAULT NULL,
  `ordem` INT NULL DEFAULT NULL,
  `apagado` INT NULL DEFAULT '0',
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` INT NOT NULL DEFAULT '1',
  `cep` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `sobre` VARCHAR(1000) NULL DEFAULT NULL,
  `logotipo` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Insert usuario teste
-- -----------------------------------------------------

INSERT INTO empresa (nome, email, senha, sobre, logoTipo, cep, endereco, numero, bairro, complemento, cidade, estado, ativo)
VALUES ('Nome da Empresa', 'teste@teste.com', '6d6cd63284be4a47ba7aec4a3458939a95dcbdd5cd0438f23d7457099b4b917c', 'Descrição da Empresa', 'caminho/para/logo.png', '12345678', 'Rua Exemplo', 123, 'Bairro Exemplo', 'Complemento Exemplo', 'Cidade Exemplo', 'UF', 1);

-- -----------------------------------------------------
-- Table `deliveryOnline`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`formapagamento` (
  `idformapagamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idformapagamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`horario` (
  `idhorario` INT NOT NULL AUTO_INCREMENT,
  `idempresa` INT NOT NULL,
  `diainicio` INT NOT NULL,
  `diafim` INT NOT NULL,
  `iniciohorarioum` VARCHAR(5) NOT NULL,
  `fimhorarioum` VARCHAR(5) NOT NULL,
  `iniciohorariodois` VARCHAR(5) NULL DEFAULT NULL,
  `fimhorariodois` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idhorario`),
  INDEX `FK_HORARIO_EMPRESA_idx` (`idempresa` ASC) VISIBLE,
  CONSTRAINT `FK_HORARIO_EMPRESA`
    FOREIGN KEY (`idempresa`)
    REFERENCES `deliveryOnline`.`empresa` (`idempresa`))
ENGINE = InnoDB
AUTO_INCREMENT = 84
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`opcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`opcional` (
  `idopcional` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tiposimples` INT NOT NULL DEFAULT '1',
  `minimo` INT NOT NULL DEFAULT '0',
  `maximo` INT NOT NULL DEFAULT '0',
  `apagado` INT NULL DEFAULT '0',
  PRIMARY KEY (`idopcional`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`opcionalitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`opcionalitem` (
  `idopcionalitem` INT NOT NULL AUTO_INCREMENT,
  `idopcional` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `apagado` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idopcionalitem`),
  INDEX `FK_OPCIONAL_ITEM_idx` (`idopcional` ASC) VISIBLE,
  CONSTRAINT `FK_OPCIONAL_ITEM`
    FOREIGN KEY (`idopcional`)
    REFERENCES `deliveryOnline`.`opcional` (`idopcional`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`pedidostatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`pedidostatus` (
  `idpedidostatus` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpedidostatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`taxaentregatipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`taxaentregatipo` (
  `idtaxaentregatipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ativo` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idtaxaentregatipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`taxaentrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`taxaentrega` (
  `idtaxaentrega` INT NOT NULL AUTO_INCREMENT,
  `idtaxaentregatipo` INT NOT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `distancia` DECIMAL(10,2) NULL DEFAULT NULL,
  `tempominimo` INT NULL DEFAULT NULL,
  `tempomaximo` INT NULL DEFAULT NULL,
  `ativo` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idtaxaentrega`),
  INDEX `FK_TAXA_ENTREGA_TIPO_idx` (`idtaxaentregatipo` ASC) VISIBLE,
  CONSTRAINT `FK_TAXA_ENTREGA_TIPO`
    FOREIGN KEY (`idtaxaentregatipo`)
    REFERENCES `deliveryOnline`.`taxaentregatipo` (`idtaxaentregatipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`tipoentrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`tipoentrega` (
  `idtipoentrega` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tempominimo` INT NULL DEFAULT NULL,
  `tempomaximo` INT NULL DEFAULT NULL,
  `ativo` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idtipoentrega`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `idpedidostatus` INT NOT NULL,
  `idtipoentrega` INT NOT NULL,
  `idtaxaentrega` INT NULL DEFAULT NULL,
  `idformapagamento` INT NOT NULL,
  `troco` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `nomecliente` VARCHAR(255) NOT NULL,
  `telefonecliente` VARCHAR(255) NOT NULL,
  `datacadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datafinalizado` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `FK_PEDIDO_TIPO_ENTREGA_idx` (`idtipoentrega` ASC) VISIBLE,
  INDEX `FK_PEDIDO_TAXA_ENTREGA_idx` (`idtaxaentrega` ASC) VISIBLE,
  INDEX `FK_PEDIDO_STATUS_idx` (`idpedidostatus` ASC) VISIBLE,
  INDEX `FK_PEDIDO_FORMA_PAG_idx` (`idformapagamento` ASC) VISIBLE,
  CONSTRAINT `FK_PEDIDO_FORMA_PAG`
    FOREIGN KEY (`idformapagamento`)
    REFERENCES `deliveryOnline`.`formapagamento` (`idformapagamento`),
  CONSTRAINT `FK_PEDIDO_STATUS`
    FOREIGN KEY (`idpedidostatus`)
    REFERENCES `deliveryOnline`.`pedidostatus` (`idpedidostatus`),
  CONSTRAINT `FK_PEDIDO_TAXA_ENTREGA`
    FOREIGN KEY (`idtaxaentrega`)
    REFERENCES `deliveryOnline`.`taxaentrega` (`idtaxaentrega`),
  CONSTRAINT `FK_PEDIDO_TIPO_ENTREGA`
    FOREIGN KEY (`idtipoentrega`)
    REFERENCES `deliveryOnline`.`tipoentrega` (`idtipoentrega`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NULL DEFAULT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(500) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `ordem` INT NULL DEFAULT NULL,
  `apagado` INT NULL DEFAULT '0',
  PRIMARY KEY (`idproduto`),
  INDEX `FK_CATEGORIA_PRODUTO_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `FK_CATEGORIA_PRODUTO`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `deliveryOnline`.`categoria` (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 107
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`pedidoitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`pedidoitem` (
  `idpedidoitem` INT NOT NULL AUTO_INCREMENT,
  `idpedido` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `observacao` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idpedidoitem`),
  INDEX `FK_PRODUTO_PEDIDO_idx` (`idproduto` ASC) VISIBLE,
  INDEX `FK_PEDIDO_PRODUTO_idx` (`idpedido` ASC) VISIBLE,
  CONSTRAINT `FK_PEDIDO_PRODUTO`
    FOREIGN KEY (`idpedido`)
    REFERENCES `deliveryOnline`.`pedido` (`idpedido`),
  CONSTRAINT `FK_PRODUTO_PEDIDO`
    FOREIGN KEY (`idproduto`)
    REFERENCES `deliveryOnline`.`produto` (`idproduto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`pedidoitemopcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`pedidoitemopcional` (
  `idpedidoitemopcional` INT NOT NULL AUTO_INCREMENT,
  `idpedidoitem` INT NOT NULL,
  `idopcionalitem` INT NOT NULL,
  PRIMARY KEY (`idpedidoitemopcional`),
  INDEX `FK_PEDIDO_ITEM_idx` (`idpedidoitem` ASC) VISIBLE,
  INDEX `FK_OPCIONAL_ITEM_idx` (`idopcionalitem` ASC) VISIBLE,
  CONSTRAINT `FK_PEDIDO_ITEM`
    FOREIGN KEY (`idpedidoitem`)
    REFERENCES `deliveryOnline`.`pedidoitem` (`idpedidoitem`),
  CONSTRAINT `FK_PEDIDO_OPCIONAL_ITEM`
    FOREIGN KEY (`idopcionalitem`)
    REFERENCES `deliveryOnline`.`opcionalitem` (`idopcionalitem`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `deliveryOnline`.`produtoopcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deliveryOnline`.`produtoopcional` (
  `idprodutoopcional` INT NOT NULL AUTO_INCREMENT,
  `idproduto` INT NOT NULL,
  `idopcional` INT NOT NULL,
  PRIMARY KEY (`idprodutoopcional`),
  INDEX `FK_PRODUTO_OPCIONAL_idx` (`idproduto` ASC) VISIBLE,
  INDEX `FK_OPCIONAL_PRODUTO_idx` (`idopcional` ASC) VISIBLE,
  CONSTRAINT `FK_OPCIONAL_PRODUTO`
    FOREIGN KEY (`idopcional`)
    REFERENCES `deliveryOnline`.`opcional` (`idopcional`),
  CONSTRAINT `FK_PRODUTO_OPCIONAL`
    FOREIGN KEY (`idproduto`)
    REFERENCES `deliveryOnline`.`produto` (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;